on:
  push:
    branches:
    - main

name: 'create-table'

jobs:
  create-table:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_TOKEN: ${{ secrets.WORKFLOWS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.WORKFLOWS }}

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
      - name: Setup R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2

      - name: Create table
        run: |
          source("inst/create_markdown_table.R")
        shell: Rscript {0}
      - name: Commit and push changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.WORKFLOWS }}
          commit_prefix: "[AUTO]"
          commit_message: "update markdown table"
          target_branch: update-table
          add_timestamp: true
      - name: Get branch name
        run: |
          git branch --show-current

      - name: Create pull request
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.WORKFLOWS }}
          target_branch: main
          reviewer: PietrH
          label: update markdown table
          get_diff: false
